site_name: himena
site_description: An infinitely extensible and reusable applications framework.
repo_name: himena
repo_url: https://github.com/hanjinliu/himena

copyright: Copyright (c) 2024 - 2024 Hanjin Liu

theme:
  name: material
  features:
    - content.code.annotate
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.share
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Index: index.md
  - Tutorial: tutorial.md
  - Usage:
    - Index: usage/index.md
    - Basics: usage/basics.md
    - Tab/Window Manipulation: usage/tab_and_window.md
    - Workflows: usage/workflows.md
    - Sessions: usage/sessions.md
    - Customization: usage/customization.md
    - Built-in Widgets: usage/builtin_widgets.md
    - Built-in Dock Widgets: usage/builtin_dock_widgets.md
  - Developer's Guide:
    - Index: dev/index.md
    - The WidgetDataModel Standard: dev/widget_data_model.md
    - Plugin System: dev/plugin_system.md
    - Reader/Writer Functions: dev/io_provider.md
    - Register Functions: dev/register_functions.md
    - Register Widgets: dev/register_widgets.md
    - Register Dock Widgets: dev/register_dock_widgets.md
    - Plotting in Himena: dev/plotting.md
  - API Reference:
    - api/consts.md
    - api/layout.md
    - api/profile.md
    - api/plugins.md
    - api/types.md
    - api/standards/model_meta.md
    - api/standards/plotting.md
    - api/standards/roi.md
    - api/widgets.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: numpy
            show_source: true
            show_bases: false
            show_signature_annotations: true
            extensions:
            - griffe_fieldz: {include_inherited: true}
  - gen-files:
      scripts:
        - docs/_scripts/_screenshots.py

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

hooks:
  - docs/_scripts/_hooks.py


extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js

extra_css:
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.css
